// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vrnvgasu/metrics/internal/handler (interfaces: HealthService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/health.go . HealthService
//

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHealthService is a mock of HealthService interface.
type MockHealthService struct {
	ctrl     *gomock.Controller
	recorder *MockHealthServiceMockRecorder
	isgomock struct{}
}

// MockHealthServiceMockRecorder is the mock recorder for MockHealthService.
type MockHealthServiceMockRecorder struct {
	mock *MockHealthService
}

// NewMockHealthService creates a new mock instance.
func NewMockHealthService(ctrl *gomock.Controller) *MockHealthService {
	mock := &MockHealthService{ctrl: ctrl}
	mock.recorder = &MockHealthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthService) EXPECT() *MockHealthServiceMockRecorder {
	return m.recorder
}

// CheckPing mocks base method.
func (m *MockHealthService) CheckPing(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPing", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPing indicates an expected call of CheckPing.
func (mr *MockHealthServiceMockRecorder) CheckPing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPing", reflect.TypeOf((*MockHealthService)(nil).CheckPing), ctx)
}
