// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vrnvgasu/metrics/internal/handler (interfaces: MetricService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/metric.go . MetricService
//

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	context "context"
	reflect "reflect"

	models "github.com/vrnvgasu/metrics/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricService is a mock of MetricService interface.
type MockMetricService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricServiceMockRecorder
	isgomock struct{}
}

// MockMetricServiceMockRecorder is the mock recorder for MockMetricService.
type MockMetricServiceMockRecorder struct {
	mock *MockMetricService
}

// NewMockMetricService creates a new mock instance.
func NewMockMetricService(ctrl *gomock.Controller) *MockMetricService {
	mock := &MockMetricService{ctrl: ctrl}
	mock.recorder = &MockMetricServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricService) EXPECT() *MockMetricServiceMockRecorder {
	return m.recorder
}

// AllMetrics mocks base method.
func (m *MockMetricService) AllMetrics(arg0 context.Context) (models.MetricsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllMetrics", arg0)
	ret0, _ := ret[0].(models.MetricsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllMetrics indicates an expected call of AllMetrics.
func (mr *MockMetricServiceMockRecorder) AllMetrics(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllMetrics", reflect.TypeOf((*MockMetricService)(nil).AllMetrics), arg0)
}

// CreateOrUpdate mocks base method.
func (m *MockMetricService) CreateOrUpdate(arg0 context.Context, arg1 models.MetricsList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockMetricServiceMockRecorder) CreateOrUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockMetricService)(nil).CreateOrUpdate), arg0, arg1)
}

// FindByTypeAndID mocks base method.
func (m *MockMetricService) FindByTypeAndID(ctx context.Context, mtype models.MetricType, id string) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTypeAndID", ctx, mtype, id)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTypeAndID indicates an expected call of FindByTypeAndID.
func (mr *MockMetricServiceMockRecorder) FindByTypeAndID(ctx, mtype, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTypeAndID", reflect.TypeOf((*MockMetricService)(nil).FindByTypeAndID), ctx, mtype, id)
}
