// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vrnvgasu/metrics/internal/service/audit (interfaces: Observer)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go . Observer
//

// Package mock_audit is a generated GoMock package.
package mock_audit

import (
	reflect "reflect"

	audit "github.com/vrnvgasu/metrics/internal/service/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockObserver) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockObserverMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObserver)(nil).Close))
}

// Observe mocks base method.
func (m *MockObserver) Observe(arg0 audit.EventMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Observe", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Observe indicates an expected call of Observe.
func (mr *MockObserverMockRecorder) Observe(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockObserver)(nil).Observe), arg0)
}
