// reset — утилита кодогенерации: создает метод Reset() для структур,
// помеченных комментарием // generate:reset.
//
// Запуск из корня проекта:
//
//	go run ./cmd/reset/ .
//
// Для каждого пакета, где найдены помеченные структуры, создается файл
// reset.gen.go рядом с исходными файлами пакета.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

var primitiveZero = map[string]string{
	"any":        "nil",
	"bool":       "false",
	"byte":       "0",
	"complex128": "0",
	"complex64":  "0",
	"error":      "nil",
	"float32":    "0",
	"float64":    "0",
	"int":        "0",
	"int16":      "0",
	"int32":      "0",
	"int64":      "0",
	"int8":       "0",
	"rune":       "0",
	"string":     `""`,
	"uint":       "0",
	"uint16":     "0",
	"uint32":     "0",
	"uint64":     "0",
	"uint8":      "0",
	"uintptr":    "0",
}

// genFileTemplate — шаблон генерируемого файла.
const genFileTemplate = `// Code generated by reset; DO NOT EDIT.

package {{.Package}}
{{range .Structs}}
func ({{.Recv}} *{{.Name}}) Reset() {
if {{.Recv}} == nil {
return
}
{{.Body}}}
{{end}}`

type fileData struct {
	Package string
	Structs []structData
}

type structData struct {
	Name string
	Recv string
	Body string
}

type structMeta struct {
	name   string
	fields []*ast.Field
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}

	type dirEntry struct {
		pkg     string
		structs []structMeta
	}

	dirs := map[string]*dirEntry{}

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}

		fset := token.NewFileSet()
		pkgMap, parseErr := parser.ParseDir(fset, path, func(fi os.FileInfo) bool {
			n := fi.Name()
			return !strings.HasSuffix(n, "_test.go") && n != "reset.gen.go"
		}, parser.ParseComments)
		if parseErr != nil {
			return nil
		}

		// pkgMap: имя пакета → *ast.Package
		for pkgName, pkg := range pkgMap {
			for _, file := range pkg.Files {
				found := collectStructs(file)
				if len(found) == 0 {
					continue
				}
				if dirs[path] == nil {
					dirs[path] = &dirEntry{pkg: pkgName}
				}
				dirs[path].structs = append(dirs[path].structs, found...)
			}
		}
		return nil
	})
	if err != nil {
		panic(err)
	}

	// Компилируем шаблон один раз — он будет использован для всех пакетов.
	tmpl := template.Must(template.New("reset").Parse(genFileTemplate))
	for dir, entry := range dirs {
		data := buildFileData(entry.pkg, entry.structs)
		if err = writeGenFile(tmpl, dir, data); err != nil {
			fmt.Fprintf(os.Stderr, "generate %s: %v\n", dir, err)
			os.Exit(1)
		}
		fmt.Printf("generated: %s/reset.gen.go\n", dir)
	}
}

func collectStructs(f *ast.File) []structMeta {
	var result []structMeta

	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}

		if !docHasResetTag(gd.Doc) { // нет тега // generate:reset — пропускаем
			continue
		}

		// для  type ( A struct{}; B struct{} )
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			var fields []*ast.Field
			if st.Fields != nil {
				fields = st.Fields.List
			}
			result = append(result, structMeta{name: ts.Name.Name, fields: fields})
		}
	}
	return result
}

func docHasResetTag(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if c.Text == "// generate:reset" {
			return true
		}
	}
	return false
}

func buildFileData(pkg string, structs []structMeta) fileData {
	data := fileData{Package: pkg}
	for _, s := range structs {
		// Имя получателя — первая буква имени структуры в нижнем регистре.
		// Например, "Metrics" → "m", "ResetableStruct" → "r".
		recv := strings.ToLower(string(s.name[0]))

		var sb strings.Builder
		for _, field := range s.fields {
			if len(field.Names) == 0 {
				continue
			}
			for _, name := range field.Names {
				code := resetCode(recv+"."+name.Name, field.Type)
				if code != "" {
					sb.WriteString(code)
					sb.WriteByte('\n')
				}
			}
		}
		data.Structs = append(data.Structs, structData{
			Name: s.name,
			Recv: recv,
			Body: sb.String(),
		})
	}
	return data
}

func resetCode(expr string, typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.Ident:
		if zv, ok := primitiveZero[t.Name]; ok {
			return fmt.Sprintf("%s = %s", expr, zv)
		}

		return fmt.Sprintf(
			"if resetter, ok := interface{}(&%s).(interface{ Reset() }); ok { resetter.Reset() }",
			expr,
		)
	case *ast.StarExpr:
		return ptrResetCode(expr, t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("%s = %s[:0]", expr, expr)
		}
		return ""
	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", expr)
	case *ast.SelectorExpr:
		return fmt.Sprintf(
			"if resetter, ok := interface{}(&%s).(interface{ Reset() }); ok { resetter.Reset() }",
			expr,
		)
	}
	return ""
}

func ptrResetCode(expr string, inner ast.Expr) string {
	wrap := func(body string) string {
		return fmt.Sprintf("if %s != nil { %s }", expr, body)
	}

	switch t := inner.(type) {
	case *ast.Ident:
		if zv, ok := primitiveZero[t.Name]; ok {
			return wrap(fmt.Sprintf("*%s = %s", expr, zv))
		}

		return wrap(fmt.Sprintf(
			"if resetter, ok := interface{}(%s).(interface{ Reset() }); ok { resetter.Reset() }",
			expr,
		))
	case *ast.ArrayType:
		if t.Len == nil {
			return wrap(fmt.Sprintf("*%s = (*%s)[:0]", expr, expr))
		}

		return ""
	case *ast.MapType:
		return wrap(fmt.Sprintf("clear(*%s)", expr))
	case *ast.SelectorExpr:
		return wrap(fmt.Sprintf(
			"if resetter, ok := interface{}(%s).(interface{ Reset() }); ok { resetter.Reset() }",
			expr,
		))
	}
	return ""
}

func writeGenFile(tmpl *template.Template, dir string, data fileData) error {
	var buf bytes.Buffer

	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("template: %w", err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w\nraw output:\n%s", err, buf.String())
	}

	return os.WriteFile(filepath.Join(dir, "reset.gen.go"), src, 0644)
}
