// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vrnvgasu/metrics/internal/grpc (interfaces: Publisher)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/publisher.go . Publisher
//

// Package mock_grpc is a generated GoMock package.
package mock_grpc

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockPublisher) Notify(ctx context.Context, metricIDList []string, ip string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify", ctx, metricIDList, ip)
}

// Notify indicates an expected call of Notify.
func (mr *MockPublisherMockRecorder) Notify(ctx, metricIDList, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockPublisher)(nil).Notify), ctx, metricIDList, ip)
}
