package exitcheck

import (
	"go/parser"
	"go/token"
	"testing"
)

func TestIsGenerated(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "regular file",
			src:  "package main\n",
			want: false,
		},
		{
			name: "generated file",
			src:  "// Code generated by tool. DO NOT EDIT.\npackage main\n",
			want: true,
		},
		{
			name: "file with unrelated comments",
			src:  "// just a comment\npackage main\n",
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, "", tt.src, parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}
			if got := isGenerated(f); got != tt.want {
				t.Errorf("isGenerated() = %v, want %v", got, tt.want)
			}
		})
	}
}
